// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvHgq77f7AgOCFFYuKnDSPlNytBb4fhZw',
    appId: '1:710425914444:web:965e2b3a9bcf2aa2d298e9',
    messagingSenderId: '710425914444',
    projectId: 'laundry-9eaca',
    authDomain: 'laundry-9eaca.firebaseapp.com',
    storageBucket: 'laundry-9eaca.appspot.com',
    measurementId: 'G-216EQESHM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WE-s6OuS0KfzhgY8qSj3l38gFr9D0PI',
    appId: '1:710425914444:android:61ba7cb049d67d81d298e9',
    messagingSenderId: '710425914444',
    projectId: 'laundry-9eaca',
    storageBucket: 'laundry-9eaca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC54KH0URnZVTx31oJ70Fdk8YwUpFHjQq8',
    appId: '1:710425914444:ios:ec51966719987734d298e9',
    messagingSenderId: '710425914444',
    projectId: 'laundry-9eaca',
    storageBucket: 'laundry-9eaca.appspot.com',
    iosClientId: '710425914444-aao3of7r3cugc7jd03on9efi51gkko0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC54KH0URnZVTx31oJ70Fdk8YwUpFHjQq8',
    appId: '1:710425914444:ios:ec51966719987734d298e9',
    messagingSenderId: '710425914444',
    projectId: 'laundry-9eaca',
    storageBucket: 'laundry-9eaca.appspot.com',
    iosClientId: '710425914444-aao3of7r3cugc7jd03on9efi51gkko0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryCourse',
  );
}
